name: Build & Push Docker Image

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем код (обязательно!)
      - name: Checkout code
        uses: actions/checkout@v4

      # ❌ МЫ УДАЛИЛИ ШАГИ "Set up Java" и "Build with Maven"
      # Они больше не нужны, так как сборка происходит внутри Dockerfile

      # 2. Логин в GitHub Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Сборка и отправка
      # Docker сам скачает Maven, соберет проект и упакует результат
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest