name: Build & Push Docker Image

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем файлы репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Логинимся в реестр (чтобы можно было загрузить результат)
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. ВСЯ МАГИЯ ТУТ:
      # Мы просто говорим Докеру "Собери".
      # Он сам скачает Maven, скомпилирует Java и упакует JAR внутри контейнера.
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest