BEGIN;

ALTER TABLE categories
DROP COLUMN IF EXISTS color,
    DROP COLUMN IF EXISTS type,
    DROP COLUMN IF EXISTS color,
    DROP COLUMN IF EXISTS icon,
    DROP COLUMN IF EXISTS parent_id;

COMMIT;